import { cn } from "@/lib/utils";

/**
 * The landing's product shot: real captures of the dashboard, framed once for a
 * wide screen and once for a phone. No sliders and no stitched halves — a
 * screenshot of the actual app, in a frame that matches the device it was taken
 * on. The assets live in `public/landing-views` and are regenerated by
 * `.tmp-review/landing/mock-asset.mjs` and `mobile-shot.mjs` after any change to
 * the dashboard, so what the page shows is what the app looks like.
 * `scripts/optimize-landing-views.sh` then writes the WebP sibling each capture
 * is served as, and must be re-run whenever the JPEGs change.
 */

/** The browser chrome the desktop capture sits in. */
function BrowserChrome() {
  return (
    <div
      aria-hidden
      className="flex items-center gap-2 border-b bg-muted/60 px-3 py-2"
    >
      <span className="flex gap-1.5">
        <span className="h-2.5 w-2.5 rounded-full bg-red-400/80" />
        <span className="h-2.5 w-2.5 rounded-full bg-amber-400/80" />
        <span className="h-2.5 w-2.5 rounded-full bg-emerald-400/80" />
      </span>
      <span className="ml-1 truncate rounded-md bg-background/80 px-2 py-0.5 font-mono text-[11px] tracking-tight text-muted-foreground">
        ghosted.boo
      </span>
    </div>
  );
}

/**
 * One capture, in the two formats it ships as.
 *
 * WebP first with the JPEG as the fallback: same picture, roughly half the
 * bytes. The `loading` attribute matters as much as the format, though. Every
 * capture here exists twice — once per theme, and once per device — and the
 * variant that does not apply is `display:none`. An image that is never laid out
 * is never intersected, so a lazy one is never fetched: that is what stops a
 * light-mode desktop visit from downloading the dark screenshots and both
 * phone captures. Marking any of these eager (or giving it a priority hint)
 * brings the whole 900 KB back, because the element is in the HTML either way.
 */
function Shot({
  name,
  theme,
  width,
  height,
  alt,
  decorative = false,
  className,
}: {
  name: string;
  theme: "light" | "dark";
  width: number;
  height: number;
  alt: string;
  decorative?: boolean;
  className?: string;
}) {
  return (
    <picture className="contents">
      <source type="image/webp" srcSet={`/landing-views/${name}-${theme}.webp`} />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={`/landing-views/${name}-${theme}.jpg`}
        width={width}
        height={height}
        alt={alt}
        aria-hidden={decorative}
        loading="lazy"
        decoding="async"
        className={className}
      />
    </picture>
  );
}

/** Wide screens: the board, in a window, with the app's own header on top. */
function DesktopShot() {
  return (
    <div className="hidden overflow-hidden rounded-xl border bg-card shadow-xl lg:-mt-[11.5rem] lg:block">
      <BrowserChrome />
      {(["light", "dark"] as const).map((theme) => (
        <Shot
          key={theme}
          name="appbar"
          theme={theme}
          width={1280}
          height={57}
          alt=""
          decorative
          className={cn("w-full border-b", theme === "dark" ? "hidden dark:block" : "block dark:hidden")}
        />
      ))}
      {/* The capture that matches the theme the page is in: the landing follows
          the OS, so the screenshots have to follow it too. */}
      {(["light", "dark"] as const).map((theme) => (
        <Shot
          key={theme}
          name="board"
          theme={theme}
          width={1280}
          height={743}
          alt={
            theme === "light"
              ? "The Ghosted dashboard in board view: applications as cards grouped by stage."
              : ""
          }
          decorative={theme === "dark"}
          className={cn("w-full", theme === "dark" ? "hidden dark:block" : "block dark:hidden")}
        />
      ))}
    </div>
  );
}

/**
 * Phones: the same section as a phone, not a shrunken browser — a bezel around a
 * capture taken at phone width. A browser window on a phone tells the visitor
 * about a device they are not holding.
 */
function MobileShot() {
  return (
    /* Pulled up into the hero's band and pushed out to the page gutters: a phone
       mock floating over the section break reads as a product shot, one sitting
       politely inside its own white box reads as a diagram. */
    <div className="-mt-[7.1rem] w-full sm:hidden">
      <div className="mx-auto aspect-[9/16] w-full max-w-[21rem] rounded-[1.7rem] border bg-card shadow-xl">
        <div className="h-full overflow-hidden rounded-[1.5rem] bg-card">
          {(["light", "dark"] as const).map((theme) => (
            <Shot
              key={theme}
              name="board-mobile"
              theme={theme}
              width={780}
              height={1386}
              alt={
                theme === "light"
                  ? "The Ghosted dashboard on a phone: the board view, with applications as cards per stage."
                  : ""
              }
              decorative={theme === "dark"}
              className={cn(
                "h-full w-full object-cover object-top",
                theme === "dark" ? "hidden dark:block" : "block dark:hidden",
              )}
            />
          ))}
        </div>
      </div>
    </div>
  );
}

/**
 * The middle band (640–1023px) gets a landscape tablet: a phone capture would
 * look like a phone that ate the screen, and the desktop window is too wide to
 * read at that size. Same thin border as the other two, 16:10 as an iPad held
 * sideways.
 */
function TabletShot() {
  return (
    <div className="-mt-[8.3rem] hidden w-full sm:block lg:hidden">
      <div className="mx-auto aspect-[16/10] w-full max-w-[40rem] overflow-hidden rounded-[1.2rem] border bg-card shadow-xl">
        {(["light", "dark"] as const).map((theme) => (
          <Shot
            key={theme}
            name="board-tablet"
            theme={theme}
            width={2048}
            height={1280}
            alt={
              theme === "light"
                ? "The Ghosted dashboard on a landscape tablet: the board view, with applications as cards grouped by stage."
                : ""
            }
            decorative={theme === "dark"}
            className={cn("h-full w-full object-cover object-top", theme === "dark" ? "hidden dark:block" : "block dark:hidden")}
          />
        ))}
      </div>
    </div>
  );
}

export function LandingMock() {
  return (
    <>
      <DesktopShot />
      <TabletShot />
      <MobileShot />
    </>
  );
}
